INSERT INTO cancoes (titulo, trecho, interprete, genero_bpm, link_referencia) VALUES ('ESQUECI DE TE ESQUECER', '...', 'Revelação', 'Am', 'https://www.youtube.com/watch?v=xxxx');
INSERT INTO cancoes (titulo, trecho, interprete, genero_bpm, link_referencia) VALUES ('NOVOS', '...', 'Revelação', 'A', '');
INSERT INTO cancoes (titulo, trecho, interprete, genero_bpm, link_referencia) VALUES ('OUTDOOR / CURTINDO A VIDA', '...', 'Thiaguinho Tardezinha', '', '');
INSERT INTO cancoes (titulo, trecho, interprete, genero_bpm, link_referencia) VALUES ('TROVÃO', '...', 'Dilsinho', 'D', '');
INSERT INTO cancoes (titulo, trecho, interprete, genero_bpm, link_referencia) VALUES ('COMO NUNCA AMEI', '...', 'Exaltasamba', 'C', '');
INSERT INTO cancoes (titulo, trecho, interprete, genero_bpm, link_referencia) VALUES ('LIVRE PRA VOAR', '...', 'Thiaguinho', '', '');
INSERT INTO cancoes (titulo, trecho, interprete, genero_bpm, link_referencia) VALUES ('DONO E REFÉM', '...', 'Exaltasamba', 'D', '');
INSERT INTO cancoes (titulo, trecho, interprete, genero_bpm, link_referencia) VALUES ('CIGANA', '...', 'Ludmilla', 'Bm', '');
INSERT INTO cancoes (titulo, trecho, interprete, genero_bpm, link_referencia) VALUES ('ELEVADOR', '...', '', 'Em', '');
INSERT INTO cancoes (titulo, trecho, interprete, genero_bpm, link_referencia) VALUES ('SINAIS', '...', '', '', '');
INSERT INTO cancoes (titulo, trecho, interprete, genero_bpm, link_referencia) VALUES ('REINVENTAR', '...', '', '', '');
INSERT INTO cancoes (titulo, trecho, interprete, genero_bpm, link_referencia) VALUES ('FULMINANTE', '...', '', '', '');
INSERT INTO cancoes (titulo, trecho, interprete, genero_bpm, link_referencia) VALUES ('PRIMEIRO BEIJO', '...', '', '', '');
INSERT INTO cancoes (titulo, trecho, interprete, genero_bpm, link_referencia) VALUES ('CHEIA DE MANIAS', '...', '', '', '');
INSERT INTO cancoes (titulo, trecho, interprete, genero_bpm, link_referencia) VALUES ('TÁ ESCRITO', '...', '', '', '');
INSERT INTO cancoes (titulo, trecho, interprete, genero_bpm, link_referencia) VALUES ('JÁ DOEU', '...', '', 'E ou C#m7', '');
INSERT INTO cancoes (titulo, trecho, interprete, genero_bpm, link_referencia) VALUES ('CLIMATIZAR', '...', '', '', '');
INSERT INTO cancoes (titulo, trecho, interprete, genero_bpm, link_referencia) VALUES ('POR FAVOR', '...', '', '', '');
INSERT INTO cancoes (titulo, trecho, interprete, genero_bpm, link_referencia) VALUES ('ALUCINADO', '...', '', '', '');
INSERT INTO cancoes (titulo, trecho, interprete, genero_bpm, link_referencia) VALUES ('CAMISA 10', '...', '', '', '');